{
 "title": "Hitron CODA Cable Modem Metrics",
 "time": { "from": "2022-05-08T05:33:26.857Z", "to": "2022-05-08T12:48:08.319Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(hitron_coda_up, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(hitron_coda_up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "timerange",
    "label": "Time Range",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,2d,3d,5d,7d,14d,28d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Download (bytes/s)",
   "type": "gauge",
   "description": "Displays the average Download speed over the past 5m on the WAN interface.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Current Upload (bytes/s)",
   "type": "gauge",
   "description": "Displays the average Upload speed over the past 5m on the WAN interface.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime (last $timerange)",
   "type": "stat",
   "description": "Uptime percentile over last $timerange.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hitron_coda_up{job=~\"$job\", instance=~\"$instance\"}[$timerange])"
    }
   ]
  },
  {
   "title": "Cable Modem Uptime",
   "type": "stat",
   "description": "Uses the LAN interface's uptime as a proxy for how long the device has been powered on. _May not be accurate!_",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hitron_coda_router_lan_uptime_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "LAN Uptime"
    }
   ]
  },
  {
   "title": "WAN Uptime",
   "type": "stat",
   "description": "Time since WAN interface was brought up.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hitron_coda_router_wan_uptime_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "WAN Uptime"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "stat",
   "description": "Displays general information about the device",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_version_info{job=~\"$job\", instance=~\"$instance\"}) by (hw_version, model, serial, sw_version, vendor)"
    }
   ]
  },
  {
   "title": "Router Information",
   "type": "stat",
   "description": "Displays general information about the device's router capabilities",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hitron_coda_router_sys_info{job=~\"$job\", instance=~\"$instance\"}) by (lan_ip, rf_mac, wan_ip4, wan_ip6, router_mode, dns4, dns6)"
    }
   ]
  },
  {
   "title": "Current Download (bps)",
   "type": "gauge",
   "description": "Displays the average Download speed over the past 5m on the WAN interface.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Current Upload (bps)",
   "type": "gauge",
   "description": "Displays the average Upload speed over the past 5m on the WAN interface.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Data Usage (last $timerange)",
   "type": "stat",
   "description": "Data (bytes) received and transmitted within the last $timerange",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange])",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "increase(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange])",
     "legendFormat": "Uploaded"
    }
   ]
  },
  {
   "title": "DHCP Lease Expiry",
   "type": "stat",
   "description": "The DHCP lease will expire in this amount of time.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hitron_coda_cm_dhcp_lease_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "DHCP Lease Expiry"
    }
   ]
  },
  {
   "title": "WAN Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAN Usage (bytes/s)",
   "type": "timeseries",
   "description": "Bytes/sec received/transmitted on the WAN interface",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "WAN Usage (avg bps over $timerange)",
   "type": "timeseries",
   "description": "Bytes/sec received/transmitted on the WAN interface, averaged over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:]) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "WAN Usage (bytes per $timerange)",
   "type": "timeseries",
   "description": "Total bytes received/transmitted on the WAN interface over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "WAN Average Packet Size",
   "type": "timeseries",
   "description": "Displays the average size (in bytes) per packet seen on the WAN interface.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(hitron_coda_router_wan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]) / increase(hitron_coda_router_wan_receive_packets_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(hitron_coda_router_wan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]) / increase(hitron_coda_router_wan_transmit_packets_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "WAN Usage (packets/s)",
   "type": "timeseries",
   "description": "Packets/sec received/transmitted on the WAN interface",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(hitron_coda_router_wan_receive_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(hitron_coda_router_wan_transmit_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "WAN Usage (avg packets/s over $timerange)",
   "type": "timeseries",
   "description": "Packets/s received/transmitted on the WAN interface, averaged over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_wan_receive_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:])",
     "legendFormat": "Received"
    },
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_wan_transmit_packets_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "WAN Usage (packets per $timerange)",
   "type": "timeseries",
   "description": "Total packets received/transmitted on the WAN interface over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hitron_coda_router_wan_receive_packets_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(hitron_coda_router_wan_transmit_packets_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "LAN Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "LAN Usage (bytes/s)",
   "type": "timeseries",
   "description": "Bytes/sec received/transmitted on the LAN interface",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(hitron_coda_router_lan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(hitron_coda_router_lan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "LAN Usage (avg bps over $timerange)",
   "type": "timeseries",
   "description": "Bytes/sec received/transmitted on the LAN interface, averaged over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_lan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "avg_over_time(sum(irate(hitron_coda_router_lan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))[$timerange:]) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "LAN Usage (bytes per $timerange)",
   "type": "timeseries",
   "description": "Total bytes received/transmitted on the LAN interface over the last $timerange",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(hitron_coda_router_lan_receive_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(hitron_coda_router_lan_transmit_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$timerange]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "DOCSIS Metrics (by port)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream Signal Strength (dBmV)",
   "type": "timeseries",
   "description": "Signal strength in decibels per millivolt per channel on the downstream channels",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_downstream_signal_strength_dbmv{job=~\"$job\", instance=~\"$instance\"}) by (port)",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Downstream Signal-to-noise ratio",
   "type": "timeseries",
   "description": "Signal-to-noise ratio in decibels per channel on the downstream channels",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_downstream_signal_noise_ratio_db{job=~\"$job\", instance=~\"$instance\"}) by (port)",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Downstream Corrected/Uncorrected blocks (last $timerange)",
   "type": "timeseries",
   "description": "Count (per $timerange) of errored blocks which were either corrected or not.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hitron_coda_cm_downstream_corrected_blocks{job=~\"$job\", instance=~\"$instance\"}[$timerange])) by (port)",
     "legendFormat": "{{port}}: Corrected"
    },
    {
     "expr": "sum(increase(hitron_coda_cm_downstream_uncorrected_blocks{job=~\"$job\", instance=~\"$instance\"}[$timerange])) by (port)",
     "legendFormat": "{{port}}: Uncorrected"
    }
   ]
  },
  {
   "title": "Upstream Signal Strength (dBmV)",
   "type": "timeseries",
   "description": "Plots the upstream signal strength, in dBmV (dB above/below 1 mV). Unused ports with a strength of 0dBmV are omitted.\n\nUsually these values will remain constant, but some fluctuation can occur over time.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_upstream_signal_strength_dbmv{job=~\"$job\", instance=~\"$instance\"}) by (port) > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Downstream Active Ports",
   "type": "stat",
   "description": "Currently-active downstream channels. This usually stays static under normal operation.",
   "gridPos": { "h": 5, "w": 2, "x": 1, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hitron_coda_cm_downstream_frequency_hertz{job=~\"$job\", instance=~\"$instance\"} > 0)"
    }
   ]
  },
  {
   "title": "Downstream Overview",
   "type": "table",
   "description": "Overview of each downstream channel",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_downstream_frequency_hertz{job=~\"$job\", instance=~\"$instance\"}) by (channel, port, modulation)"
    },
    {
     "expr": "sum(hitron_coda_cm_downstream_signal_noise_ratio_db{job=~\"$job\", instance=~\"$instance\"}) by (channel, port)"
    },
    {
     "expr": "sum(hitron_coda_cm_downstream_signal_strength_dbmv{job=~\"$job\", instance=~\"$instance\"}) by (channel, port)"
    }
   ]
  },
  {
   "title": "Upstream Overview",
   "type": "table",
   "description": "Overview of each upstream channel",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hitron_coda_cm_upstream_frequency_hertz{job=~\"$job\", instance=~\"$instance\"}) by (channel, port, modulation)"
    },
    {
     "expr": "sum(hitron_coda_cm_upstream_bandwidth_bytes_per_second{job=~\"$job\", instance=~\"$instance\"}) by (channel, port) * 8"
    },
    {
     "expr": "sum(hitron_coda_cm_upstream_signal_strength_dbmv{job=~\"$job\", instance=~\"$instance\"}) by (channel, port)"
    }
   ]
  },
  {
   "title": "Upstream Active Ports",
   "type": "stat",
   "description": "Currently-active upstream channels. This usually stays static under normal operation.",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hitron_coda_cm_upstream_frequency_hertz{job=~\"$job\", instance=~\"$instance\"} > 0)"
    }
   ]
  }
 ]
}